name: Firebase Deployment
on:
  push:
    branches:
      - main
      - devbranch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          CI: true
          # VITE_WEBHOOK: ${{ secrets.VITE_WEBHOOK }}
          # VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Set Firebase Project
        id: firebase_project
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "FIREBASE_PROJECT=gilper-org" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "devbranch" ]; then
            echo "FIREBASE_PROJECT=gilper-org-test" >> $GITHUB_ENV
          else
            echo "unknown branch, skipping deployment"
            exit 1
          fi
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project ${{ env.FIREBASE_PROJECT }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GILPER }}
